### ISSUE TITLE
Need support for EIP 1577

### ISSUE THREAD

**Issue by homotopycolimit** [ensdomains/ens-manager#50]
Any name in ENS that is set up using the 'default public resolver' (using manager.ens.domains, or manager-beta.ens.domains for example) will now be using a new resolver that conforms to EIP 1577.

https://eips.ethereum.org/EIPS/eip-1577

As such, the content field has changed to contenthash and the app no longer works with this resolver for setting content hashes.

The app should be updated to check what the resolver supports and act accordingly.

**Comment by jefflau** [comment]
Thanks for this. We won't be updating this manager anymore as we are in the middle of building out this functionality in the new ENS app, which you can currently beta test at manager-beta.ens.domains

I will be updating the content field to contenthash once we've 100% settled on the spec

**Comment by homotopycolimit** [comment]
I didn't know where to file for the manager-beta. It has the same issue... but I see that you are aware already :)

**Comment by jeluard** [comment]
@jefflau Is the beta thing still relevant? I have a hard time to test EIP1577 with the currently deployed manager.
I can provide more details if that's helpful.
